name: push workflow

on:
  push:
    paths:
      - psychopy_linux_installer
      - .github/workflows/**
      - .github/PsychoPy_tests/**
  workflow_dispatch:

jobs:
  # Initial syntax check
  syntax-check:
    uses: ./.github/workflows/reusable_syntax_check.yaml
  
  # Test installation with build
  test-installation-quick:
    needs: syntax-check
    if: success()
    uses: ./.github/workflows/reusable_test.yaml
    with:
      quick-mode: true