name: push workflow

on:
  push:
    paths:
      - psychopy_linux_installer
  workflow_dispatch:

jobs:
  # Initial syntax check
  syntax-check:
    uses: ./.github/workflows/reusable_syntax_check.yaml

  # Test installation in quick-mode
  test-installation-quick:
    needs: syntax-check
    uses: ./.github/workflows/reusable_test.yaml
    with:
      test-mode: "quick"
