name: reusable copy release assets

on:
  workflow_call:

jobs:
  copy-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy assets from previous release to current release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -e
          INSTALLER_VERSION=$(./psychopy_linux_installer --version)
          RELEASE_TAG="v${INSTALLER_VERSION}"

          # Get all releases
          RELEASES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases")

          # Find previous release (not current)
          PREV_RELEASE=$(echo "$RELEASES" | jq 'map(select(.tag_name != "'"$RELEASE_TAG"'")) | sort_by(.created_at) | reverse | .[0]')
          PREV_ID=$(echo "$PREV_RELEASE" | jq -r '.id')
          PREV_TAG=$(echo "$PREV_RELEASE" | jq -r '.tag_name')

          # Get current release upload URL and list of existing asset names
          CUR_RELEASE=$(echo "$RELEASES" | jq 'map(select(.tag_name == "'"$RELEASE_TAG"'")) | .[0]')
          UPLOAD_URL=$(echo "$CUR_RELEASE" | jq -r '.upload_url' | sed 's/{?name,label}//')
          EXISTING_ASSETS=$(echo "$CUR_RELEASE" | jq -r '.assets[].name')

          # Download all assets from previous release except those that already exist in the current release
          ASSETS=""
          PAGE=1
          while :; do
            RESPONSE=$(curl -s -D - -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/$PREV_ID/assets?per_page=100&page=$PAGE")
            BODY=$(echo "$RESPONSE" | sed -n '/^\r$/,$p' | sed '1d')
            ASSETS=$(echo "$ASSETS"; echo "$BODY")
            # Check for next page in Link header
            LINK_HEADER=$(echo "$RESPONSE" | grep -i '^Link:')
            if echo "$LINK_HEADER" | grep -q 'rel="next"'; then
              PAGE=$((PAGE+1))
            else
              break
            fi
          done
          ASSETS=$(echo "$ASSETS" | jq -s 'add')

          echo "$ASSETS" | jq -r '.[] | [.name, .url] | @tsv' | while IFS=$'\t' read -r name url; do
            if echo "$EXISTING_ASSETS" | grep -qx "$name"; then
              echo "Skipping $name (already exists in current release)"
              continue
            fi
            echo "Transferring asset: $name"
            curl -sS -L -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/octet-stream" "$url" \
              | curl -sS -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/octet-stream" \
                --data-binary @- "$UPLOAD_URL?name=$name"
          done

          # Get asset names for previous and current releases
          PREV_ASSETS=$(echo "$PREV_RELEASE" | jq -r '.assets[].name' | sort)
          CUR_ASSETS=$(echo "$CUR_RELEASE" | jq -r '.assets[].name' | sort)

          # Compare: show assets in previous release not in current
          MISSING_ASSETS=$(comm -23 <(echo "$PREV_ASSETS") <(echo "$CUR_ASSETS"))

          if [ -z "$MISSING_ASSETS" ]; then
            echo "All assets from previous release are present in the current release."
          else
            echo "Missing assets in current release:"
            echo "$MISSING_ASSETS"
            exit 1
          fi