name: reusable check release

on:
  workflow_call:
    outputs:
      result:
        value: ${{ jobs.check-release.outputs.result }}
jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.release-checker.outputs.result }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Installer Version
        run: |
          INSTALLER_VERSION=$(grep -m1 '^# *Version:' psychopy_linux_installer | sed 's/^# *Version: *//')
          echo "INSTALLER_VERSION=$INSTALLER_VERSION" >> $GITHUB_ENV
          if [ -z "$INSTALLER_VERSION" ]; then
            echo "Error: Failed to extract version from script."
            exit 1
          fi

      - name: Check if release exists
        id: release-checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          RELEASE_TAG="v${INSTALLER_VERSION}"
          API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${RELEASE_TAG}"
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$API_URL")
          
          if echo "$RESPONSE" | grep -q '"id":'; then
            echo "Release ${RELEASE_TAG} already exists."
            echo "result=no_release" >> $GITHUB_OUTPUT
          else
            echo "No existing release for version ${RELEASE_TAG}."
            echo "result=release" >> $GITHUB_OUTPUT
          fi